
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: iiko
  password: koi8rus
  host: localhost
  reconnect: true

development:
  <<: *default
  database: iiko_<%=branch%>_db

test:
  <<: *default
  database: iiko_test_db


production:
  <<: *default
  database: iiko_db
